# Generated by Django 4.1.3 on 2022-11-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorDeProyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mes', models.DateField()),
                ('AvanceIngenieria', models.IntegerField()),
                ('AvanceCompraMateriales', models.IntegerField()),
                ('AvanceMontaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Costos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Codigo', models.CharField(max_length=50)),
                ('Mes', models.DateField()),
                ('CostoIngenieria', models.IntegerField()),
                ('CostoMateriales', models.IntegerField()),
                ('CostoMontaje', models.IntegerField()),
                ('CostoInspeccion', models.IntegerField()),
            ],
        ),
    ]
